### ISSUE TITLE
中文翻译版发现个错别字

### ISSUE THREAD

**Issue by titancat** [Jinjiang/vuejs.org#23]
在[视图](http://jinjiang.github.io/vuejs.org/guide/#视图_\(View\))的那个部分

> Vue.js 使用基于 DOM 的模板。每个 Vue 实例都关联着一个相应的 DOM 元素。当一个 Vue 实例被创建时，它会递归便利根元素的所有子结点，同时完成必要的数据绑定。当这个视图被编译之后，它就会自动反映数据的变化。

应该是「遍历」而不是「遍利」。 :)

**Comment by Jinjiang** [comment]
非常感谢！晚上回家修掉

**Comment by titancat** [comment]
刚刚刷微博的时候，发现vue有个[中文站](http://vuejs.net/)。

**Comment by Jinjiang** [comment]
我昨天也发现了，还有 Vue.js 作者的回复：http://weibo.com/1712131295/C1JWC2JRh?type=comment#_rnd1422594938466
