### ISSUE TITLE
感谢所有贡献者！

### ISSUE THREAD

**Issue by yyx990803** [Jinjiang/vuejs.org#25]
尤其是锦江~ 么么哒

**Comment by Jinjiang** [comment]
大家都很给力，来接受 Vue.js 作者的致谢吧：）
@etanxing
@fengliu222
@Garfielt
@getive
@kunth
@luin
@nkCoding
@skyline0705
@SoAanyip
@Suixinlei
@titancat
@XfLoops

**Comment by luin** [comment]
（≧∇≦）

**Comment by Suixinlei** [comment]
:-)

**Comment by fengliu222** [comment]
耶~

**Comment by nkCoding** [comment]
感谢 @yyx990803 带来Vue.js~  感谢 @Jinjiang 的组织~ :tada:

**Comment by kunth** [comment]
^_^

**Comment by titancat** [comment]
nice job!

**Comment by Garfielt** [comment]
^_^ Good!

**Comment by qusiba** [comment]
谢谢

**Comment by Jinjiang** [comment]
Hi 童鞋们
`v0.12` 的文档来啦 :smile: 欢迎大家继续来这里领任务了：https://github.com/Jinjiang/vuejs.org/wiki#v012 先提前谢过大家的支持！！
同时这个 issue 我关掉了

祝好
