### ISSUE TITLE
API中文翻译存在的问题

### ISSUE THREAD

**Issue by titancat** [Jinjiang/vuejs.org#35]
1. 在 [Liftcycle](http://cn.vuejs.org/api/options.html#Lifecycle) 这里
     > 所有的生命周期的this都Vue实例。

     少了个「是」？

2. 在 [vm.$$](http://cn.vuejs.org/api/instance-properties.html#vm-\$\$) 这里的
     > Read only

     为啥不翻译为「只读」？

3. 在[vm.$broadcast( event, [args…] )](http://cn.vuejs.org/api/instance-methods.html#vm-\$broadcast\(_event\,_\[args…\]_\))
    >为当前 vm 的所有子 vm 注册该事件，这个 vm 会一直传播到到他的子vm。当一个回调返回 false 。当一个回调返回了 false，那么它的所有者实例就不会广播这个事件了。

  `当一个回调返回 false`这句重复了？

**Comment by Jinjiang** [comment]
非常感谢！问题已修复:-)
