### ISSUE TITLE
认领directives部分

### ISSUE THREAD

**Issue by skyline0705** [Jinjiang/vuejs.org#37]

**Comment by Jinjiang** [comment]
Hi，想跟你核实一下，这里领取的 directives 是 `guide` 目录下的还是 `api` 目录下的？我之前理解是 `guide` 目录下的，最近 @lvdou 把 `api` 目录下的 directives 领走了，希望不要搞重复了：）

谢谢

**Comment by skyline0705** [comment]
Guide的下的正在翻译中。
最近一直在加班，今晚会把剩余部分翻译好提pr，实在实在抱歉……

**Comment by Jinjiang** [comment]
能理解，所以你看我建议任务一份一份领吧 :smile:

**Comment by skyline0705** [comment]
下次一定量力而行，主要是之前认领的时候没那么忙，刚认领之后就开始忙成🐶😢
