### ISSUE TITLE
$watch的使用翻译问题

### ISSUE THREAD

**Issue by chenboxiang** [Jinjiang/vuejs.org#39]
![image](https://cloud.githubusercontent.com/assets/1421876/8246762/7464b29c-1676-11e5-8dc1-24a00aa079fe.png)

图片中标红的部分翻译错误了， 原本的意思是不需要 deep 就可以 watch 数组的变化
但是 non-deep watcher 只能 watch 数组本身结构的变化，deep watcher 可以 watch 数组包含的对象里面的变化，但是代价会比较高。

**Comment by Jinjiang** [comment]
我正好在更新这份文档的翻译，会一起处理一下
谢谢

**Comment by Jinjiang** [comment]
fixed in c2f486c8a03edc2840f99b9be714734460c7ce56

**Comment by chenboxiang** [comment]
赞
