### ISSUE TITLE
感谢所有 0.12.x 的贡献者！

### ISSUE THREAD

**Issue by Jinjiang** [Jinjiang/vuejs.org#67]
@lvdou
@FTAndy
@nkCoding
@skyline0705
@getive
@chaoren1641

谢谢大家 都非常给力！

同时 0.12.8 的计划已经启动了，欢迎大家继续来这里领任务: https://github.com/Jinjiang/vuejs.org/wiki#v0128 :smile:

**Comment by Jinjiang** [comment]
0.12.8 也已经翻译完成！再次感谢

@fkysly
@lvdou
@FTAndy
@nkCoding

接下来开放所有人 review + 校对文档了：）

**Comment by yyx990803** [comment]
:clap: :clap: :clap:
