### ISSUE TITLE
这里明确区别一下 property 和 attribute 的译法等翻译注意事项

### ISSUE THREAD

**Issue by Jinjiang** [Jinjiang/vuejs.org#74]
Hi 各位译者，最近在 review 的时候发现这两个词大家的译法不太相同，由于中文有很多种译法且相互难以完全从字面上区分，所以这里希望可以统一一下：

- property 译作“属性”
- attribute 译作“特性”

同时这个译法也是 W3C 中文兴趣组翻译的众多技术文档中约定的译法。

谢谢

@fkysly
@FTAndy
@nkCoding
@lvdou

**Comment by Jinjiang** [comment]
还有一些细节约定是：

1. 中英文之间加空格
2. 所有的圆括号用半角圆括号且圆括号和外部中文之间要加空格

如果大家翻译到的地方发现不符，不妨顺手修正一下

**Comment by yyx990803** [comment]
:+1: 

另外有一位同学很给力地一个人翻译了全部文档：http://vuejs.hongfanqie.org/ 大家可以对照参考一下，看看有什么歧义或是可以改进的地方。

**Comment by FTAndy** [comment]
@yanxyz

**Comment by yanxyz** [comment]
呃，那我就冒下泡吧，周末在微博上私信 @Jinjiang，大概是没有看到，没有收到回复。源码我还没放到 github 上，有些问题邮件问过 @yyx990803 后做了调整，整个翻译基本结束，剩下来有一些我可能没注意的书写错误，一些句子感觉还要调整一下。不过作为参照没有问题。

因为是重译，不方便合并这个库中，不然把大家的翻译都覆盖了。

这个库是按标签一步步翻译到最新版，我是直接拿最新版翻译。

翻译要求建议整理到 wiki 当中，也可以出一份术语表。我的翻译符合这个 issue 中提到的要求。翻译至少句子要通顺，以减轻审校的工作量。

建议更新认领统一放到一个 issue 中，方便查看。

**Comment by Jinjiang** [comment]
Oops，一直没有留意到私信，抱歉
翻译要求整理到 wiki 是很好的建议！翻译内容合并我暂时没有想到什么好办法，暂时想到的办法就是人肉过一遍吧……
