### ISSUE TITLE
“时间” 与 “事件”  笔误

### ISSUE THREAD

**Issue by zhy1stgg** [Jinjiang/vuejs.org#82]
>为什么要在 HTML 中写监听器？

>你可能会注意到整个事件监听的方式违背了 “separation of concern” 的传统理念。不必担心，因为所有的 Vue.js 时间处理方法和表达式都严格绑定在当前视图的 ViewModel 上，它不会导致任何维护困难。实际上，使用 v-on 还有更多好处：

这里的 ***因为所有的 Vue.js 时间处理方法*** 的时间应该是笔误吧

**Comment by Jinjiang** [comment]
多谢指正！已处理，稍后发布
