### ISSUE TITLE
vue会增加Include指令么？

### ISSUE THREAD

**Issue by 572962673** [Jinjiang/vuejs.org#84]
vue会增加Include指令么？如果考虑，那个版本会添加，我在API中没有看到这个指令，别的MVVM框架都有集成这个指令，希望VUE也能添加

**Comment by yyx990803** [comment]
不会考虑。请用异步组件：http://cn.vuejs.org/guide/components.html#异步组件

**Comment by 572962673** [comment]
谢谢
