### ISSUE TITLE
认领/source/guide/transitions.md部分

### ISSUE THREAD

**Issue by skyline0705** [Jinjiang/vuejs.org#9]

**Comment by Jinjiang** [comment]
Hi，`api/options.md` [@etanxing](https://github.com/etanxing) 已经领过了哦

**Comment by Jinjiang** [comment]
要不要再领个别的 :-)

**Comment by skyline0705** [comment]
还有哪些没人领的？我看基本都领了？要不剩下的我全认领了吧~貌似也没多少了

**Comment by Jinjiang** [comment]
那 `/api/directives.html` 和 `/guide/transitions.html 如何`？你可以先选其一

**Comment by skyline0705** [comment]
/api/directives.html吧，

**Comment by Jinjiang** [comment]
不好意思 `/api/directives.html` 刚才一瞬间也被领走了，我把 `/guide/transitions.html` 留给你了 - -

**Comment by skyline0705** [comment]
好吧~那就transitions吧~囧~

**Comment by skyline0705** [comment]
以完成，但是不知道为什么提pull request提了两次都跑到vue/vuej.org那里去了…不太熟悉怎么弄…囧

**Comment by Jinjiang** [comment]
前几天没顾上看，应该是提交的方式不太正确，我明天抽空帮你重新提交合并一下
谢谢
